mysql:
  image: mysql:8.0
  rootPassword: rootpassword
  user: debezium
  password: dbz
  database: inventory

minio:
  image: minio/minio
  rootUser: admin
  rootPassword: password
  bucket: warehouse

mc:
  image: minio/mc
  commands:
    - alias minio=/usr/bin/mc
    - minio alias set myminio http://minio:9000 admin password
    - minio mb myminio/warehouse

rest:
  image: apache/iceberg-rest-fixture
  environment:
    awsAccessKeyId: admin
    awsSecretAccessKey: password
    awsRegion: us-east-1
    catalogWarehouse: s3://warehouse/
    catalogIoImpl: org.apache.iceberg.aws.s3.S3FileIO
    catalogS3Endpoint: http://minio:9000
    catalogS3PathStyleAccess: "true"
    catalogS3SslEnabled: "false"